/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PharmaTrace {
  export type BatchStruct = {
    id: BigNumberish;
    batchCode: string;
    productName: string;
    manufacturer: AddressLike;
    currentCustodian: AddressLike;
    manufacturedAt: BigNumberish;
    expiresAt: BigNumberish;
    metadataHash: BytesLike;
    documentHash: BytesLike;
    state: BigNumberish;
    exists: boolean;
  };

  export type BatchStructOutput = [
    id: bigint,
    batchCode: string,
    productName: string,
    manufacturer: string,
    currentCustodian: string,
    manufacturedAt: bigint,
    expiresAt: bigint,
    metadataHash: string,
    documentHash: string,
    state: bigint,
    exists: boolean
  ] & {
    id: bigint;
    batchCode: string;
    productName: string;
    manufacturer: string;
    currentCustodian: string;
    manufacturedAt: bigint;
    expiresAt: bigint;
    metadataHash: string;
    documentHash: string;
    state: bigint;
    exists: boolean;
  };
}

export interface PharmaTraceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "DISTRIBUTOR_ROLE"
      | "LOGISTICS_ROLE"
      | "MANUFACTURER_ROLE"
      | "PHARMACY_ROLE"
      | "REGULATOR_ROLE"
      | "acceptTransfer"
      | "createBatch"
      | "getBatch"
      | "getRoleAdmin"
      | "grantRole"
      | "grantSupplyChainRole"
      | "hasRole"
      | "pause"
      | "paused"
      | "pendingTransfers"
      | "recallBatch"
      | "recordCheckpoint"
      | "renounceRole"
      | "requestTransfer"
      | "revokeRole"
      | "revokeSupplyChainRole"
      | "supportsInterface"
      | "totalBatches"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchRecalled"
      | "BatchRegistered"
      | "CheckpointRecorded"
      | "Paused"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "TransferAccepted"
      | "TransferRequested"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DISTRIBUTOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LOGISTICS_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MANUFACTURER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PHARMACY_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REGULATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptTransfer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createBatch",
    values: [string, string, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBatch",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantSupplyChainRole",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingTransfers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recallBatch",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordCheckpoint",
    values: [BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestTransfer",
    values: [BigNumberish, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeSupplyChainRole",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalBatches",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DISTRIBUTOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LOGISTICS_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MANUFACTURER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PHARMACY_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REGULATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBatch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "grantSupplyChainRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingTransfers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recallBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordCheckpoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeSupplyChainRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalBatches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace BatchRecalledEvent {
  export type InputTuple = [
    batchId: BigNumberish,
    actor: AddressLike,
    recallHash: BytesLike
  ];
  export type OutputTuple = [
    batchId: bigint,
    actor: string,
    recallHash: string
  ];
  export interface OutputObject {
    batchId: bigint;
    actor: string;
    recallHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BatchRegisteredEvent {
  export type InputTuple = [
    batchId: BigNumberish,
    batchCode: string,
    productName: string,
    manufacturer: AddressLike,
    metadataHash: BytesLike,
    documentHash: BytesLike,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    batchId: bigint,
    batchCode: string,
    productName: string,
    manufacturer: string,
    metadataHash: string,
    documentHash: string,
    expiresAt: bigint
  ];
  export interface OutputObject {
    batchId: bigint;
    batchCode: string;
    productName: string;
    manufacturer: string;
    metadataHash: string;
    documentHash: string;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CheckpointRecordedEvent {
  export type InputTuple = [
    batchId: BigNumberish,
    actor: AddressLike,
    newState: BigNumberish,
    checkpointHash: BytesLike
  ];
  export type OutputTuple = [
    batchId: bigint,
    actor: string,
    newState: bigint,
    checkpointHash: string
  ];
  export interface OutputObject {
    batchId: bigint;
    actor: string;
    newState: bigint;
    checkpointHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferAcceptedEvent {
  export type InputTuple = [
    batchId: BigNumberish,
    from: AddressLike,
    to: AddressLike
  ];
  export type OutputTuple = [batchId: bigint, from: string, to: string];
  export interface OutputObject {
    batchId: bigint;
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferRequestedEvent {
  export type InputTuple = [
    batchId: BigNumberish,
    from: AddressLike,
    to: AddressLike,
    shipmentHash: BytesLike
  ];
  export type OutputTuple = [
    batchId: bigint,
    from: string,
    to: string,
    shipmentHash: string
  ];
  export interface OutputObject {
    batchId: bigint;
    from: string;
    to: string;
    shipmentHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PharmaTrace extends BaseContract {
  connect(runner?: ContractRunner | null): PharmaTrace;
  waitForDeployment(): Promise<this>;

  interface: PharmaTraceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DISTRIBUTOR_ROLE: TypedContractMethod<[], [string], "view">;

  LOGISTICS_ROLE: TypedContractMethod<[], [string], "view">;

  MANUFACTURER_ROLE: TypedContractMethod<[], [string], "view">;

  PHARMACY_ROLE: TypedContractMethod<[], [string], "view">;

  REGULATOR_ROLE: TypedContractMethod<[], [string], "view">;

  acceptTransfer: TypedContractMethod<
    [batchId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createBatch: TypedContractMethod<
    [
      batchCode: string,
      productName: string,
      expiresAt: BigNumberish,
      metadataHash: BytesLike,
      documentHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  getBatch: TypedContractMethod<
    [batchId: BigNumberish],
    [PharmaTrace.BatchStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  grantSupplyChainRole: TypedContractMethod<
    [account: AddressLike, role: BytesLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingTransfers: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string, boolean] & {
        from: string;
        to: string;
        requestedAt: bigint;
        shipmentHash: string;
        exists: boolean;
      }
    ],
    "view"
  >;

  recallBatch: TypedContractMethod<
    [batchId: BigNumberish, recallHash: BytesLike],
    [void],
    "nonpayable"
  >;

  recordCheckpoint: TypedContractMethod<
    [batchId: BigNumberish, checkpointHash: BytesLike, nextState: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  requestTransfer: TypedContractMethod<
    [batchId: BigNumberish, to: AddressLike, shipmentHash: BytesLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeSupplyChainRole: TypedContractMethod<
    [account: AddressLike, role: BytesLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  totalBatches: TypedContractMethod<[], [bigint], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DISTRIBUTOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LOGISTICS_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MANUFACTURER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PHARMACY_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "REGULATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "acceptTransfer"
  ): TypedContractMethod<[batchId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createBatch"
  ): TypedContractMethod<
    [
      batchCode: string,
      productName: string,
      expiresAt: BigNumberish,
      metadataHash: BytesLike,
      documentHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBatch"
  ): TypedContractMethod<
    [batchId: BigNumberish],
    [PharmaTrace.BatchStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "grantSupplyChainRole"
  ): TypedContractMethod<
    [account: AddressLike, role: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingTransfers"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string, boolean] & {
        from: string;
        to: string;
        requestedAt: bigint;
        shipmentHash: string;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "recallBatch"
  ): TypedContractMethod<
    [batchId: BigNumberish, recallHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordCheckpoint"
  ): TypedContractMethod<
    [batchId: BigNumberish, checkpointHash: BytesLike, nextState: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestTransfer"
  ): TypedContractMethod<
    [batchId: BigNumberish, to: AddressLike, shipmentHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeSupplyChainRole"
  ): TypedContractMethod<
    [account: AddressLike, role: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalBatches"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "BatchRecalled"
  ): TypedContractEvent<
    BatchRecalledEvent.InputTuple,
    BatchRecalledEvent.OutputTuple,
    BatchRecalledEvent.OutputObject
  >;
  getEvent(
    key: "BatchRegistered"
  ): TypedContractEvent<
    BatchRegisteredEvent.InputTuple,
    BatchRegisteredEvent.OutputTuple,
    BatchRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "CheckpointRecorded"
  ): TypedContractEvent<
    CheckpointRecordedEvent.InputTuple,
    CheckpointRecordedEvent.OutputTuple,
    CheckpointRecordedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TransferAccepted"
  ): TypedContractEvent<
    TransferAcceptedEvent.InputTuple,
    TransferAcceptedEvent.OutputTuple,
    TransferAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "TransferRequested"
  ): TypedContractEvent<
    TransferRequestedEvent.InputTuple,
    TransferRequestedEvent.OutputTuple,
    TransferRequestedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "BatchRecalled(uint256,address,bytes32)": TypedContractEvent<
      BatchRecalledEvent.InputTuple,
      BatchRecalledEvent.OutputTuple,
      BatchRecalledEvent.OutputObject
    >;
    BatchRecalled: TypedContractEvent<
      BatchRecalledEvent.InputTuple,
      BatchRecalledEvent.OutputTuple,
      BatchRecalledEvent.OutputObject
    >;

    "BatchRegistered(uint256,string,string,address,bytes32,bytes32,uint64)": TypedContractEvent<
      BatchRegisteredEvent.InputTuple,
      BatchRegisteredEvent.OutputTuple,
      BatchRegisteredEvent.OutputObject
    >;
    BatchRegistered: TypedContractEvent<
      BatchRegisteredEvent.InputTuple,
      BatchRegisteredEvent.OutputTuple,
      BatchRegisteredEvent.OutputObject
    >;

    "CheckpointRecorded(uint256,address,uint8,bytes32)": TypedContractEvent<
      CheckpointRecordedEvent.InputTuple,
      CheckpointRecordedEvent.OutputTuple,
      CheckpointRecordedEvent.OutputObject
    >;
    CheckpointRecorded: TypedContractEvent<
      CheckpointRecordedEvent.InputTuple,
      CheckpointRecordedEvent.OutputTuple,
      CheckpointRecordedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "TransferAccepted(uint256,address,address)": TypedContractEvent<
      TransferAcceptedEvent.InputTuple,
      TransferAcceptedEvent.OutputTuple,
      TransferAcceptedEvent.OutputObject
    >;
    TransferAccepted: TypedContractEvent<
      TransferAcceptedEvent.InputTuple,
      TransferAcceptedEvent.OutputTuple,
      TransferAcceptedEvent.OutputObject
    >;

    "TransferRequested(uint256,address,address,bytes32)": TypedContractEvent<
      TransferRequestedEvent.InputTuple,
      TransferRequestedEvent.OutputTuple,
      TransferRequestedEvent.OutputObject
    >;
    TransferRequested: TypedContractEvent<
      TransferRequestedEvent.InputTuple,
      TransferRequestedEvent.OutputTuple,
      TransferRequestedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
